version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: card_management_db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: card_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - card-network

  app:
    build: .
    container_name: card_management_app
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/card_management_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_PROFILES_ACTIVE: docker
      APP_ENCRYPTION_KEY: ${APP_ENCRYPTION_KEY_ENV:-AAECAwQFBgcICQoLDA0ODw==}
      APP_JWT_SECRET: ${APP_JWT_SECRET_ENV:-VGhpcyBpcyBhIHZlcnkgc3Ryb25nIGFuZCBzZWNyZXQga2V5IGZvciBK V1QgYXV0aGVudGljYXRpb24uIERvIG5vdCBzaGFyZSBpdCE=}
      APP_JWT_EXPIRATION_MS: ${APP_JWT_EXPIRATION_MS_ENV:-3600000}
    networks:
      - card-network

volumes:
  postgres_data:

networks:
  card-network:
    driver: bridge
