server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcard_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  secret: secret-key
  expiration: 86400000 # 1 день
