server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

app:
  encryption:
    key: AAECAwQFBgcICQoLDA0ODw==
  card:
    expiry-check:
      cron: 0 0 1 * * ?
  jwt:
    secret: K4kMouU6Lx/FAa1YuaO+UFFzPjUvnzUkBMvvKWuJhXDvcHHznWR0yH6mn9rFjpC/NpesxDgj+QNkxs0T3YffNQ==
    expiration-ms: 86400000
